/* eslint global-require: 0 */

const iNaturalistAPI = require( "./inaturalist_api" );

module.exports = {
  setConfig: iNaturalistAPI.setConfig,
  annotations: require( "./endpoints/annotations" ),
  authorized_applications: require( "./endpoints/authorized_applications" ),
  comments: require( "./endpoints/comments" ),
  computervision: require( "./endpoints/computervision" ),
  controlled_terms: require( "./endpoints/controlled_terms" ),
  flags: require( "./endpoints/flags" ),
  identifications: require( "./endpoints/identifications" ),
  messages: require( "./endpoints/messages" ),
  observation_field_values: require( "./endpoints/observation_field_values" ),
  observation_photos: require( "./endpoints/observation_photos" ),
  observation_sounds: require( "./endpoints/observation_sounds" ),
  observations: require( "./endpoints/observations" ),
  photos: require( "./endpoints/photos" ),
  places: require( "./endpoints/places" ),
  posts: require( "./endpoints/posts" ),
  projects: require( "./endpoints/projects" ),
  project_observations: require( "./endpoints/project_observations" ),
  project_users: require( "./endpoints/project_users" ),
  provider_authorizations: require( "./endpoints/provider_authorizations" ),
  relationships: require( "./endpoints/relationships" ),
  search: require( "./endpoints/search" ),
  sites: require( "./endpoints/sites" ),
  sounds: require( "./endpoints/sounds" ),
  taxa: require( "./endpoints/taxa" ),
  translations: require( "./endpoints/translations" ),
  users: require( "./endpoints/users" ),
  Annotation: require( "./models/annotation" ),
  Comment: require( "./models/comment" ),
  ControlledTerm: require( "./models/controlled_term" ),
  Flag: require( "./models/flag" ),
  Identification: require( "./models/identification" ),
  Observation: require( "./models/observation" ),
  ObservationFieldValue: require( "./models/observation_field_value" ),
  Photo: require( "./models/photo" ),
  Place: require( "./models/place" ),
  Post: require( "./models/post" ),
  Project: require( "./models/project" ),
  ProjectUser: require( "./models/project_user" ),
  ProviderAuthorization: require( "./models/provider_authorization" ),
  Site: require( "./models/site" ),
  Taxon: require( "./models/taxon" ),
  User: require( "./models/user" ),
  FileUpload: require( "./models/file_upload" )
};
